name: map_rps
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5
  - torchvision
  - torchaudio
  - pip

  - pip:
      - einops
      - omegaconf
      - lpips
      - scikit-image
      - torch-fidelity