model:
  type: 'sd15'
  # model_id: "runwayml/stable-diffusion-v1-5"
  model_id: "/nas/datasets/stable-diffusion-v1-5/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14/"
data:
    dataset: "coco"
    image_size: 512
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32