model:
  type: 'sd15'
  model_id: "runwayml/stable-diffusion-v1-5"
data:
    dataset: "coco"
    image_size: 512
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32